id: IB500CBBA
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:06:56.921637+00:00
last_modified: 2022-12-14 18:06:56.921646+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-068-004
  eft-text-version: 1.1.8 2020
  title: Toh_270-The_Seven_Buddhas-v2
bases:
  226A:
    source_metadata: null
    order: 1
    base_file: 226A.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
